# Generated by Django 5.2.8 on 2025-11-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhDThesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pmid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
