# Generated by Django 5.2.8 on 2025-11-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_phdthesis_alter_publication_journal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phdthesis',
            old_name='institution',
            new_name='university',
        ),
        migrations.AddField(
            model_name='phdthesis',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
